[keyboard]
name = "Cygtyl"
product_name = "Cygtyl"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Noir Guo"
chip = "nrf52840"

[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true
rows = 6
cols = 12
layers = 5
keymap = [
    [
        ["Escape", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Backspace"],
        ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "Backslash"],
        ["CapsLock", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote"],
        ["LShift", "Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash", "WM(Enter,RShift)"],
        ["_", "_", "_", "LAlt", "Enter", "MO(2)", "PageUp", "PageDown", "WM(Minus,RAlt)", "_", "_", "_"],
        ["_", "_", "_", "_", "_", "_", "Left", "PageDown", "Down", "Right", "Up", "_"]
    ],
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false

# !!! Warning: RMK uses last 2 sectors of your microcontroller's flash by default. You have to ensure that those flash space is not used.
# If you're using a bootloader which puts itself at the end of the flast, like Adafruit_nRF52_Bootloader, RMK will break the bootloader.
# Setting the `start_addr` manually to avoid this. See: https://haobogu.github.io/rmk/storage.html

[ble]
enabled = true
battery_adc_pin = "vddh"


[split]
connection = "ble"


[split.central]
rows = 6
cols = 6
row_offset = 0
col_offset = 0
[split.central.matrix]
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]
output_pins = ["P0_08", "P0_31", "P0_29", "P0_02", "P0_17", "P0_20"]


[[split.peripheral]]
rows = 6
cols = 6
row_offset = 0
col_offset = 6
[split.peripheral.matrix]
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11", "P1_04", "P1_06"]
output_pins = ["P0_08", "P0_31", "P0_29", "P0_02", "P0_17", "P0_20"]

# 7mm鼠标编码器
[[input_device.encoder]]
pin_a = "P1_15"
pin_b = "P1_13"
internal_pullup = false
phase = "e8h7" # 24定位12脉冲，12*4/24=2
# Whether the direction of the rotary encoder is reversed.
reverse = false
