# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Pad24"
product_name = "Pad24"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "Noir Guo"
chip = "nrf52840"

[matrix]
# Input and output pins are mandatory
row_pins = ["P0_31", "P0_24", "P0_09", "P0_10", "P1_11", "P1_13"]
col_pins = ["P0_29", "P0_02", "P1_15", "P0_22"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
rows = 6
cols = 4
layers = 3
keymap = [
    [
        ["Escape", "Backspace", "Delete", "Equal"],
        ["Tab", "KpSlash", "KpAsterisk", "KpMinus"],
        ["Kp7", "Kp8", "Kp9", "KpPlus"],
        ["Kp4", "Kp5", "Kp6", "_"],
        ["Kp1", "Kp2", "Kp3", "KpEnter"],
        ["Kp0", "_", "KpDot", "_"]
    ],
    [
        ["_", "_","_", "_"],
        ["_", "_","_", "_"],
        ["_", "_","_", "_"],
        ["_", "_","_", "_"],
        ["_", "_","_", "_"],
        ["_", "_","_", "_"]
    ],
    [
        ["_", "_","_", "_"],
        ["_", "_","_", "_"],
        ["_", "_","_", "_"],
        ["_", "_","_", "_"],
        ["_", "_","_", "_"],
        ["_", "_","_", "_"]
    ],
]

[storage]
# Storage feature is enabled by default
# enabled = false

# Ble configuration
[ble]
# Whether to enable BLE feature
enabled = true
# nRF52840's saadc pin for reading battery level, you can use a pin number or "vddh"
battery_adc_pin = "vddh"
default_tx_power = 8
